import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/components/Provider";
import SessionProvider from '../components/SessionProvider'
import { getServerSession } from "next-auth";
import NavMenu from "@/components/NavMenu";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Provider>
            <main className="flex flex-row w-fit">
              <NavMenu />
              {children}
            </main>

          </Provider>
        </SessionProvider>
      </body>
    </html>
  );
}
